name: tracking_app
description: A Flutter app to track GPS and barometer altitude and export as GPX.
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^9.0.2
  flutter_barometer: ^0.1.0
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true