name: tracking_app
description: A Flutter app to track GPS + barometer altitude and export GPX.
version: 1.1.0+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^14.0.1
  path_provider: ^2.1.2
  share_plus: ^7.2.0
  fl_chart: ^0.66.2
  equations: ^5.0.0
  xml: ^6.3.0                 # F端r XML-Parsing
  file_picker: ^10.1.5        # F端r Dateiauswahl
  intl: ^0.18.1               # F端r Datums- und Zahlenformatierung
  sensors_plus: ^6.1.1
  provider: ^6.1.5
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "Flutter Application/trackin_icon_v1.png"
  adaptive_icon_background: "#FFFFFF" # Optional, f端r Android adaptive icons
  adaptive_icon_foreground: "Flutter Application/trackin_icon_v1.png" # Optional
